# The character that should surround emoji names. E.g. the emoji :smile: uses the character :
EmojiCharacter: ":"

# Each group has its own permission node and range of characters it can use.
# The range of characters are in hexadecimal and must be in the format of MIN:MAX
Groups:
  Default:
    Range:
      - "e000:e02a"
    Permission: "customchatemoji.group.default"
    Emoji:
      e000: "matsuri_pog"
  Admin:
    Range:
    - "e0e0:e0ff"
    Permission: "customchatemoji.group.admin"
